title: Game Machines
logo: /assets/img/logo.png
description: Un progetto di vendita hardware come PC gaming e periferiche, prodotti hitech e merchndising tramite dropshipping e l'utilizzo di un personal brand per fidelizzazione e marketing
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
